= Part 1 - Logging in Spring Boot Application

ifdef::env-github[]
:projectroot: https://raw.githubusercontent.com/nsalexamy/nsa2-logging-example/main
// :sourcedir: https://raw.githubusercontent.com/nsalexamy/nsa2-logging-example/main/src/main/java
:sourcedir: .
:resourcedir: https://raw.githubusercontent.com/nsalexamy/nsa2-logging-example/main/src/main/resources
endif::[]

ifndef::env-github[]
:projectroot: ../..
:sourcedir: ../../src/main/java
:resourcedir: ../../src/main/resources
endif::[]



== Introduction

Logging is an essential part of any application. It helps developers to track the application's behavior, diagnose issues, and monitor performance. In this tutorial, we will learn how to log in a Spring Boot application. We will use the SLF4J and Logback libraries to log messages in the application. We will also learn how to configure the log level and log file location in the application using the application.yml and logback.xml files. Finally, we will learn how to change the log level at runtime using the Actuator endpoints.

=== Centralized Logging series

1. Part 1 - Logging in Spring Boot Application
2. Part 2 - Centralized Logging with Fluent-bit and Elasticsearch(Kubernetes)
3. Part 3 - Centralized Logging with Fluent-bit and Elasticsearch(On-premise)
4. Part 4 - Log Analysis with Apache Spark

== Prerequisites

Before starting this tutorial, you should have the following:

- Basic knowledge of Java programming language
- Basic knowledge of Spring Boot
- Java Development Kit (JDK) installed on your machine
- Integrated Development Environment (IDE) installed on your machine
- Gradle build tool installed on your machine

== Logging in Spring Boot Application

=== Convention over Configuration

Convention over Configuration (CoC) is a software design paradigm that seeks to decrease the number of decisions that developers need to make, without losing flexibility. The idea is to set sensible defaults and standards that developers can follow, so they don't have to start from scratch every time they create a new application or feature.

Spring Boot follows the Convention over Configuration principle. It provides sensible defaults and standards for configuring various aspects of the application, such as logging, database connection, and web server configuration. This allows developers to focus on writing business logic and application features, without worrying about the underlying infrastructure.

The benefits of Convention over Configuration are:

1. Reduced boilerplate code: Developers don't have to write repetitive code to configure the application. Spring Boot provides sensible defaults and standards that can be easily customized.
2. Faster development: Developers can focus on writing business logic and application features, without getting bogged down in configuration details.
3. Consistency: Spring Boot enforces consistent coding standards and practices across the application, making it easier to maintain and scale.

=== Logging Application

There are two key files in the project:

- build.gradle.kts
- LoggingExampleApplication.java

==== build.gradle.kts

build.gradle.kts is the Gradle build script for the project. It defines the project dependencies, plugins, and tasks. The build.gradle.kts file for the project is as follows:

[source,kotlin]
----
include::{projectroot}/build.gradle.kts[]
----

==== LoggingExampleApplication.java

LoggingExampleApplication.java is the main class of the application. It contains the main method that starts the Spring Boot application. The LoggingExampleApplication.java file for the project is as follows:

.LoggingExampleApplication.java
[source,java]
----
include::{sourcedir}/com/alexamy/nsa2/example/logging/LoggingExampleApplication.java[]
----

In the LoggingExampleApplication java file, there are two log messages: one at the INFO level and one at the DEBUG level. The INFO level log message is printed when the application starts, and the DEBUG level log message is printed when the application stops.

@Slf4j is a Lombok annotation that generates a logger field in the class. The logger field is used to log messages in the application. The @Slf4j annotation is a convenient way to add logging capabilities to a class without writing boilerplate code.

The boilerplate code generated by the @Slf4j annotation is equivalent to the following code:
[source,java]
----
private static final Logger log = LoggerFactory.getLogger(LoggingExampleApplication.class);
----



.run the application using the following command:
[source,shellscript]
----
$ ./gradlew bootRun  --args="--server.port=18080 --spring.main.banner-mode=off"
----

The application will start on port 18080. You can access the application by opening a web browser and navigating to http://localhost:18080.
And --spring.main.banner-mode=off is used to disable the Spring Boot banner when the application starts.

When the application starts, you will see the following log messages in the console:
----
2024-05-23T00:29:50.132-07:00  INFO 51557 --- [nsa2-logging-example] [           main] c.a.n.e.l.LoggingExampleApplication      : Starting LoggingExampleApplication using Java 17.0.11 with PID 51557 (/Users/younggyukim/Dev/jhipster/nsa2-logging-example/build/classes/java/main started by younggyukim in /Users/younggyukim/Dev/jhipster/nsa2-logging-example)
2024-05-23T00:29:50.140-07:00  INFO 51557 --- [nsa2-logging-example] [           main] c.a.n.e.l.LoggingExampleApplication      : No active profile set, falling back to 1 default profile: "default"
2024-05-23T00:29:51.842-07:00  INFO 51557 --- [nsa2-logging-example] [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2024-05-23T00:29:52.294-07:00  INFO 51557 --- [nsa2-logging-example] [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 18080
2024-05-23T00:29:52.320-07:00  INFO 51557 --- [nsa2-logging-example] [           main] c.a.n.e.l.LoggingExampleApplication      : Started LoggingExampleApplication in 2.832 seconds (process running for 3.399)
2024-05-23T00:29:52.324-07:00  INFO 51557 --- [nsa2-logging-example] [           main] c.a.n.e.l.LoggingExampleApplication      : Application started successfully.

----

The log message at DEBUG level is not printed in the console because the default log level is INFO. To enable the DEBUG level log message, we need to customize the log level in the application.

.to enable DEBUG log level, you can run the application using the following command:
----
$ ./gradlew bootRun  --args="--server.port=18080 --spring.main.banner-mode=off --logging.level.com.alexamy.nsa2=DEBUG"
----

Now we notice that there are some default configurations for logging in Spring Boot. The default log level is INFO, and the default log file location is the console. We can customize the log level and log file location by creating a logback.xml file in the src/main/resources directory of the project. Apart from the log level, the default message format is also provided by Spring Boot.

For more information on Spring Boot logging, please refer to the following links:

- https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging
- https://docs.spring.io/spring-boot/how-to/logging.html

To collect the log messages by log collectors like Fluent-bit, it is important to understand the log format. The default log format is:

CONSOLE_LOG_PATTERN is defined in the org.springframework.boot.logging.logback.LogbackLoggingSystem class. The default value of it is defined in defaults.xml in the org/springframework/boot/logging/logback directory of the spring-boot jar file.

Here is some of the code snippet of the default value of CONSOLE_LOG_PATTERN in defaults.xml:

[source,xml]
----
<property name="CONSOLE_LOG_PATTERN" value="${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr(%applicationName[%15.15t]){faint} %clr(${LOG_CORRELATION_PATTERN:-}){faint}%clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"/>
----

To simply put, the default log format is as follows:

LOG_DATEFORMAT_PATTERN LOG_LEVEL_PATTERN PID applicationName thread logger message exception

TIP: To open files in the spring-boot jar file in IntelliJ IDEA, you can use the following steps:

1. Tap the Shift key twice to open the search dialog.
2. Type the class name you want to open, such as LogbackLoggingSystem.

== Changing the Logging Level at Runtime

In this section, I will show you how to change the log level at runtime in a Spring Boot application.

I added a couple of files to the project:

- application.yml
- LoggingExampleApi.java
- LoggingExampleController.java
- LoggingExampleService.java


Spring Boot provides a feature to change the log level at runtime using the Actuator endpoints. The Actuator endpoints are a set of RESTful web services that provide information about the application's health, metrics, and other operational aspects. The Actuator endpoints can be used to monitor and manage the application in production.

To change the log level at runtime, we need to enable the Actuator endpoints in the application. The Actuator endpoints are enabled by default in Spring Boot applications. We can access the Actuator endpoints by opening a web browser and navigating to http://localhost:18080/actuator.

.application.yml
[source,yaml]
----
spring:
  application:
    name: nsa2-logging-example
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health,loggers
  endpoint:
    loggers:
      enabled: true
----


After adding application.yml, restart the application using the following command:

[source,shellscript]
----
$ ./gradlew bootRun  --args="--server.port=18080"
----

Now, open a web browser and navigate to http://localhost:18080/actuator. You will see a list of Actuator endpoints that are available in the application.

To check the log level of a specific logger, you can use the /actuator/loggers/{logger} endpoint. For example, to check the log level of the com.alexamy.nsa2 package, you can use the following URL: http://localhost:18080/actuator/loggers/com.alexamy.nsa2.

.result of the /actuator/loggers/com.alexamy.nsa2 endpoint
[source,json]
----
{
  "effectiveLevel": "INFO"
}
----

In order to change log level at runtime, you can use the /actuator/loggers/{logger} endpoint with the POST method. For example, to change the log level of the com.alexamy.nsa2 package to DEBUG, you can use the following URL: http://localhost:18080/actuator/loggers/com.alexamy.nsa2 with the following JSON payload:

[source,json]
----
{
  "configuredLevel": "DEBUG"
}
----

Ths curl command to change the log level of the com.alexamy.nsa2 package to DEBUG is as follows:

[source,shellscript]
----
$ curl -X POST -H "Content-Type: application/json" -d '{"configuredLevel": "DEBUG"}' http://localhost:18080/actuator/loggers/com.alexamy.nsa2 -i
----

Now hit the URL http://localhost:18080/actuator/loggers/com.alexamy.nsa2 again, you will see the log level of the com.alexamy.nsa2 package is changed to DEBUG.

.result of the /actuator/loggers/com.alexamy.nsa2 endpoint after changing the log level
[source,json]
----
{
  "configuredLevel": "DEBUG",
  "effectiveLevel": "DEBUG"
}
----

Now that we have learned how to change the log level at runtime in a Spring Boot application using the Actuator endpoints, let's write some log messages in the application.

.LoggingExampleApi.java
[source,java]
----
include::{sourcedir}/com/alexamy/nsa2/example/logging/api/LoggingExampleApi.java[]
----

LoggingExampleApi.java is a RESTful web service that exposes an endpoint to log messages in the application. It contains a single method named writeLog that takes a log level as a PathVariable and a message as a RequestBody.

.LoggingExampleController.java
[source,java]
----
include::{sourcedir}/com/alexamy/nsa2/example/logging/controller/LoggingExampleController.java[]
----

LoggingExampleController.java is a Spring MVC controller that handles the incoming HTTP requests and delegates the processing to the LoggingExampleService class. It contains a single method named writeLog that maps to the /v1.0.0/log/{level} endpoint.
it returns true when the log message is successfully written. Otherwise, it returns false. If the log level is not valid, it returns false with status code 400.

.LoggingExampleService.java
[source,java]
----
include::{sourcedir}/com/alexamy/nsa2/example/logging/service/LoggingExampleService.java[]
----

LoggingExampleService.java is a service class that contains the business logic to log messages in the application. It contains a single method named writeLog that takes a log level and a message as input and logs the message at the specified log level. It uses the SLF4J logger to log messages in the application. 

Now, restart the application using the following command:
[source,shellscript]
----
$ ./gradlew bootRun  --args="--server.port=18080"
----

NOTE: The log level change is not persisted across application restarts. If you restart the application, the log level will revert to the default value. To persist the log level change across application restarts, you can store the log level in a configuration file or a database.

=== Call the API to Write Log Messages

In this section, I will show you how to call the API to write log messages in the application.

Before calling the API to write log messages, make sure that log level of the com.alexamy.nsa2 package is set to INFO by default. You can check the log level of the com.alexamy.nsa2 package and its child packages by using curl command:
[source,shellscript]
----
$ curl http://localhost:18080/actuator/loggers | jq '.loggers | to_entries[] | select(.key |  startswith("com.alexamy.nsa2")) '

{
  "key": "com.alexamy.nsa2",
  "value": {
    "effectiveLevel": "INFO"
  }
}
{
  "key": "com.alexamy.nsa2.example",
  "value": {
    "effectiveLevel": "INFO"
  }
}
{
  "key": "com.alexamy.nsa2.example.logging",
  "value": {
    "effectiveLevel": "INFO"
  }
}
{
  "key": "com.alexamy.nsa2.example.logging.LoggingExampleApplication",
  "value": {
    "effectiveLevel": "INFO"
  }
}
{
  "key": "com.alexamy.nsa2.example.logging.controller",
  "value": {
    "effectiveLevel": "INFO"
  }
}
{
  "key": "com.alexamy.nsa2.example.logging.controller.LoggingExampleController",
  "value": {
    "effectiveLevel": "INFO"
  }
}
{
  "key": "com.alexamy.nsa2.example.logging.service",
  "value": {
    "effectiveLevel": "INFO"
  }
}
{
  "key": "com.alexamy.nsa2.example.logging.service.LoggingExampleService",
  "value": {
    "effectiveLevel": "INFO"
  }
}

----

To call the API to write log messages, you can use a REST client such as Postman or cURL. You can also use the Swagger UI to call the API.

We are using cURL to call the API to write log messages. The cURL command to write a log message at the INFO level is as follows:

[source,shellscript]
----
$ curl -X POST -H "Content-Type: application/json" -d 'This is an INFO log message' http://localhost:18080/v1.0.0/log/INFO
true

$ curl -X POST -H "Content-Type: application/json" -d 'This is a DEBUG log message' http://localhost:18080/v1.0.0/log/DEBUG
false
----

Because the log level of the com.alexamy.nsa2 package is set to INFO by default, the INFO level log message is successfully written to the log file. The DEBUG level log message is not written to the log file because the log level is set to INFO.

.log messages in the console
----
2024-05-22T09:32:11.349-07:00  INFO 39459 --- [nsa2-logging-example] [           main] c.a.n.e.l.LoggingExampleApplication      : Application started successfully.
2024-05-22T09:32:44.429-07:00  INFO 39459 --- [nsa2-logging-example] [ctor-http-nio-2] c.a.n.e.l.service.LoggingExampleService  : Writing log - level: INFO, message: This is an INFO log message

----

Now, change the log level of the com.alexamy.nsa2 package to DEBUG using the Actuator endpoints like we did in the previous step

[source,shellscript]
----
$ curl -X POST -H "Content-Type: application/json" -d '{"configuredLevel": "DEBUG"}' http://localhost:18080/actuator/loggers/com.alexamy.nsa2 -i
----

And check the log level of the com.alexamy.nsa2 package to verify that the log level is changed to DEBUG.

[source,shellscript]
----
$ curl http://localhost:18080/actuator/loggers | jq '.loggers | to_entries[] | select(.key |  startswith("com.alexamy.nsa2")) '


{
  "key": "com.alexamy.nsa2",
  "value": {
    "configuredLevel": "DEBUG",
    "effectiveLevel": "DEBUG"
  }
}
{
  "key": "com.alexamy.nsa2.example",
  "value": {
    "effectiveLevel": "DEBUG"
  }
}
{
  "key": "com.alexamy.nsa2.example.logging",
  "value": {
    "effectiveLevel": "DEBUG"
  }
}
{
  "key": "com.alexamy.nsa2.example.logging.LoggingExampleApplication",
  "value": {
    "effectiveLevel": "DEBUG"
  }
}
{
  "key": "com.alexamy.nsa2.example.logging.controller",
  "value": {
    "effectiveLevel": "DEBUG"
  }
}
{
  "key": "com.alexamy.nsa2.example.logging.controller.LoggingExampleController",
  "value": {
    "effectiveLevel": "DEBUG"
  }
}
{
  "key": "com.alexamy.nsa2.example.logging.service",
  "value": {
    "effectiveLevel": "DEBUG"
  }
}
{
  "key": "com.alexamy.nsa2.example.logging.service.LoggingExampleService",
  "value": {
    "effectiveLevel": "DEBUG"
  }
}
----

Let's call the API to write a DEBUG level log message using the following cURL command:

[source,shellscript]
----
$ curl -X POST -H "Content-Type: application/json" -d 'This is a DEBUG log message' http://localhost:18080/v1.0.0/log/DEBUG

true
----

Now, check the log messages in the console. You will see that the DEBUG level log message is successfully written to the log file.

.log messages in the console
----
2024-05-22T10:39:15.981-07:00 DEBUG 39459 --- [nsa2-logging-example] [ctor-http-nio-9] c.a.n.e.l.service.LoggingExampleService  : Writing log - level: DEBUG, message: This is a DEBUG log message
----

== Customizing logging in Spring Boot

There are some ways to customize logging in Spring Boot applications. In this sections, I will show you how to customize logging in a Spring Boot application using the two

- application.yml
- logback.xml

=== Customizing using application.yml file

Here is an example of customizing logging in a Spring Boot application using the application.yml file:

[source,yaml]
----
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

  level:
    root: INFO
    com.alexamy.nsa2: DEBUG

  file:
    name: logs/nsa2-logging-example.log

  logback:
    rollingpolicy:
      max-history: 10
      file-name-pattern: logs/backup/nsa2-logging-example-%d{yyyy-MM-dd}-%2i.log
      max-file-size: 1MB

----

In the application.yml file, we have defined the following custom logging configurations:

- pattern: Defines the log message format for the console and file appenders.
- level: Defines the log level for the root logger and the com.alexamy.nsa2 package.
- file: Defines the log file location for the application.
- logback.rollingpolicy: Defines the rolling policy for the log file, such as the maximum history, file name pattern, and maximum file size.



=== Customizing using logback.xml file

Here is an example of customizing logging in a Spring Boot application using the logback.xml file which is equivalent to the application.yml file:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>
    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>logs/nsa2-logging-example.log</file>
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>logs/backup/nsa2-logging-example-%d{yyyy-MM-dd}-%2i.log</fileNamePattern>
            <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                <maxFileSize>1MB</maxFileSize>
            </timeBasedFileNamingAndTriggeringPolicy>
            <maxHistory>10</maxHistory>
            <maxFileSize>1MB</maxFileSize>
        </rollingPolicy>
    </appender>

    <logger name="com.alexamy.nsa2" level="ERROR" additivity="false">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="FILE" />
    </logger>
    <root level="INFO">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="FILE" />
    </root>
</configuration>
----

logback.xml is the configuration file for the Logback library. It is used to configure the log level and log file location in the application. if logback.xml is placed in the src/main/resources directory of the project, Spring Boot will automatically pick up the configuration and apply it to the application.

Alternatively, you can use the logback.xml file with --logging.config option to specify the location of the logback.xml file:
[source,shellscript]
----
$ ./gradlew bootRun --args="--server.port=18080 --logging.config=./logback.xml"
----

Even though both application.yml and logback.xml files can be used to customize logging in a Spring Boot application, to make things simple, it is recommended to use the application.yml file for logging configuration.

== Conclusion

In this tutorial, we learned how to log in a Spring Boot application. We used the SLF4J and Logback libraries to log messages in the application. We also learned how to configure the log level and log file location in the application using the application.yml and logback.xml files. We also learned how to change the log level at runtime using the Actuator endpoints. By following the steps in this tutorial, you can customize logging in your Spring Boot application and manage log messages effectively.

In the next tutorial, we will learn how to set up centralized logging with Fluent-bit and Elasticsearch in a Kubernetes environment. Stay tuned!

== References

- https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging[Spring Boot Logging Features]
- https://docs.spring.io/spring-boot/how-to/logging.html[How to use Spring Boot Logging]
- https://logback.qos.ch/manual/configuration.html[Logback Configuration]
- https://github.com/nsalexamy/nsa2-logging-example[Source code for the project]
