apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nsa2-logging-example
  name: nsa2-logging-example
  namespace: nsa2
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nsa2-logging-example
  type: ClusterIP
status:
  loadBalancer: {}
